# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrst',
            name='nr_st',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
