# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 11:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrst',
            name='data_przyjecia',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='nrst',
            name='dzierzawca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nrst',
            name='place',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nrst',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='nrst',
            name='uwagi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nrstc',
            name='dzierzawca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nrstc',
            name='place',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nrstc',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='nrstc',
            name='uwagi',
            field=models.TextField(null=True),
        ),
    ]
