# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170208_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrstc',
            name='data',
            field=models.DateField(default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='nrstc',
            name='nr_stc',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
