# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20170214_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrst',
            name='dzierzawca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nrst',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nrst',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nrst',
            name='uwagi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
