# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20170209_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nrstc',
            old_name='data',
            new_name='data_przyjecia',
        ),
    ]
