# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20170209_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrstc',
            name='data_przyjecia',
            field=models.DateField(default='01/01/1970', null=True),
        ),
    ]
