# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20170215_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrstc',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
