# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20170209_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrstc',
            name='data_przyjecia',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 13, 54, 42, 708589)),
        ),
    ]
