# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20170209_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrstc',
            name='data_przyjecia',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 14, 5, 23, 584175)),
        ),
    ]
