# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20170217_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
